### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by MAXOUXAX** [MAXOUXAX/Vortex#3]
```java
[12:47:46] [ForkJoinPool.commonPool-worker-0] ERROR n.d.jda.api.requests.RestAction - Encountered error while processing success consumer 
java.util.ConcurrentModificationException: null
        at java.util.ArrayList.forEach(ArrayList.java:1262)
        at me.maxouxax.vortex.forwarding.ForwardingManager.forwardMessage(ForwardingManager.java:112)
        at me.maxouxax.vortex.forwarding.TaskPullMessages.lambda$null$1(TaskPullMessages.java:25)
        at net.dv8tion.jda.api.requests.Request.lambda$onSuccess$0(Request.java:95)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

**Comment by MAXOUXAX** [comment]
Fixed in 4d42e09
